In [56]:
import numpy as np
import matplotlib.pyplot as plt
plt.close('all')
#===
N = ??????# **6
counter_A = 0
counter_B = 0
counter_outside = 0
A_pos = []
B_pos = []
for i in range(N):
    x = np.random.uniform(-1, 1)
    y = np.random.uniform(0, 1)
    if (y >= ???????):
        if (y < ???????):
            pos = (x,y)
            A_pos.append(pos)
            counter_A += 1
        else:
            pos = (x,y)
            B_pos.append(pos)
            counter_B += 1
    else:
        counter_outside += 1



plt.figure(figsize=(6, 6))
plt.scatter([pos[0] for pos in A_pos], [pos[1] for pos in A_pos], color = 'y', marker='o', \
            s = 20, alpha=1.0);
plt.scatter([pos[0] for pos in B_pos], [pos[1] for pos in B_pos], color = 'r', marker='o', \
            s = 20, alpha=1.0);

plt.xlim(-1.5,1.5)
plt.ylim(-0.5,1.5)

print (counter_A)
print (counter_B)
print (counter_outside)

total = counter_A + counter_B + counter_outside
print (total)
Square_Area = ???????
Area_A = Square_Area * counter_A/total
Area_B = Square_Area * counter_B/total
Area_Outside = Square_Area * counter_outside/total

print ("Area_A = ", Area_A)
print ("Area_B = ", Area_B)
print ("Area_Outside = ", Area_Outside)
total_area = Area_A + Area_B + Area_Outside
print ("total_area = ", total_area)
#==
sigma_A = ?????? #g/m^2
sigma_B = ?????? #g/m^2
Mass_A = Area_A * sigma_A
Mass_B = Area_B * sigma_B
Mass_Composite = Mass_A + Mass_B
print ("Mass_Composite = %.3f g"%(Mass_Composite))

SyntaxError: invalid syntax (246659023.py, line 5)

In [59]:
import numpy as np
A = np.array([[ 3., -2., 0.,  0.],
              [-2., 4., -2.,  0.],
              [ 0.,  -2.,  6., -4.],
              [ 0.,  0., -4.,  4.]])




b = np.array([0,2,1,8])

print (A)
print (b)

[[ 3. -2.  0.  0.]
 [-2.  4. -2.  0.]
 [ 0. -2.  6. -4.]
 [ 0.  0. -4.  4.]]
[0 2 1 8]


In [60]:
Sol = np.linalg.solve(A,b)
print ("Method 1 =", Sol)


Method 1 = [11.  16.5 21.  23. ]


In [61]:
A_inv = np.linalg.inv(A)
Sol2 = np.dot(A_inv, b)
print ("Method 2 =", Sol2)

Method 2 = [11.  16.5 21.  23. ]


In [68]:
A = np.array([[ 3., -2., 0.,  0.],
              [-2., 4., -2.,  0.],
              [ 0.,  -2.,  6., -4.],
              [ 0.,  0., -4.,  4.]])

D = np.array([[ 3., 0., 0.,  0.],
              [0., 4., 0.,  0.],
              [ 0.,   0., 6.,  0],
              [ 0.,  0.,  0,  4.]])

L = np.array([[ 0., 0., 0.,  0.],
              [-2., 0., 0.,  0.],
              [ 0.,  -2.,  0.,0.],
              [ 0.,  0., -4.,  0.]])

U = np.array([[ 0., -2., 0.,  0.],
              [ 0., 0., -2.,  0.],
              [ 0.,  0.,  0., -4.],
              [ 0.,  0., 0.,  0.]])

b = np.array([0,2,1,8])

u_old = np.array([0.,0.,0.,0.])
u_new = np.array([0.,0.,0.,0.])



for i in range(4):
    sigma_i = 0.
    for j in range(4):
        sigma_i += (L[i][j] + U[i][j]) *u_old[j]
    u_new[i] = 1. / D[i][i] * (b[i] - sigma_i)


print (u_old)
print (u_new)



[0. 0. 0. 0.]
[0.         0.5        0.16666667 2.        ]
